Committed the new changes

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: CI - Test, Deploy, and Reinit
+name: CI - Complie, Test, Deploy, and Reinit
 
 on:
   push:
@@ -7,10 +7,20 @@ on:
     branches: [main, staging]
 
 jobs:
+  codechecker:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+    - name: Run CodeChecker
+      uses: docker://foundeo/cfml-ci-tools:latest
+      with:
+        entrypoint: /opt/box/box
+        args: codechecker run --verbose
+
   test:
     name: Run TestBox Tests
     runs-on: ubuntu-latest
-
+    needs: codechecker
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -47,44 +57,42 @@ jobs:
 
           echo "All tests passed successfully"
 
+  # ftp_deploy:
+  #   name: FTP Deploy
+  #   runs-on: ubuntu-latest
+  #   needs: test
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
 
-  deploy:
-    name: FTP Deploy
-    runs-on: ubuntu-latest
-    needs: test
+  #     - name: FTP Deploy
+  #       uses: SamKirkland/FTP-Deploy-Action@4.3.0
+  #       with:
+  #         server: ${{ vars.FTP_SERVER }}
+  #         username: ${{ vars.FTP_USERNAME }}
+  #         password: ${{ secrets.FTP_PASSWORD }}
+  #         local-dir: ./
+  #         exclude: |
+  #           .git*
+  #           .github*
+  #           tests/*
+  #           box.json
+  #           commandbox-debian-6.2.0.deb
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+  # reinit:
+  #   name: Reinitialize Application
+  #   runs-on: ubuntu-latest
+  #   needs: [ftp_deploy]  # Only run after successful deployment
 
-      - name: FTP Deploy
-        uses: SamKirkland/FTP-Deploy-Action@4.3.0
-        with:
-          server: ${{ secrets.FTP_SERVER }}
-          username: ${{ secrets.FTP_USERNAME }}
-          password: ${{ secrets.FTP_PASSWORD }}
-          local-dir: ./
-          exclude: |
-            .git*
-            .github*
-            tests/*
-            box.json
-            commandbox-debian-6.2.0.deb
-
-  reinit:
-    name: Reinitialize Application
-    runs-on: ubuntu-latest
-    needs: deploy  # Only run after successful deployment
-
-    steps:
-      - name: Send reinit request
-        run: |
-          echo "Reinitializing application..."
-          response=$(curl -s -o /dev/null -w "%{http_code}" "${{ vars.REINIT_URL }}")
+  #   steps:
+  #     - name: Send reinit request
+  #       run: |
+  #         echo "Reinitializing application..."
+  #         response=$(curl -s -o /dev/null -w "%{http_code}" "${{ vars.REINIT_URL }}")
           
-          if [ "$response" -eq 200 ]; then
-            echo "Application reinitialized successfully"
-          else
-            echo "::error::Failed to reinitialize application. HTTP Status: $response"
-            exit 1
-          fi
+  #         if [ "$response" -eq 200 ]; then
+  #           echo "Application reinitialized successfully"
+  #         else
+  #           echo "::error::Failed to reinitialize application. HTTP Status: $response"
+  #           exit 1
+  #         fi
