Final update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,6 +28,9 @@ jobs:
           box version
 
       - name: Install dependencies and run tests
+        env:
+            TESTKEY: ${{ vars.TESTKEY }}
+
         run: |
           box install
           box install testbox
@@ -45,45 +48,43 @@ jobs:
           echo "All tests passed successfully"
 
 
-  # deploy:
-  #   name: FTP Deploy
-  #   runs-on: ubuntu-latest
-  #   needs: test
+  deploy:
+    name: FTP Deploy
+    runs-on: ubuntu-latest
+    needs: test
 
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v3
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-  #     - name: FTP Deploy
-  #       uses: SamKirkland/FTP-Deploy-Action@4.3.0
-  #       with:
-  #         server: ${{ secrets.FTP_SERVER }}
-  #         username: ${{ secrets.FTP_USERNAME }}
-  #         password: ${{ secrets.FTP_PASSWORD }}
-  #         local-dir: ./
-  #         server-dir: ${{ secrets.FTP_DEPLOY_DIR }}/  # Should end with /
-  #         exclude: |
-  #           **/.git*
-  #           **/.github*
-  #           **/tests*
-  #           **/test-results.json
-  #           **/box.json
-  #           **/commandbox-debian-6.2.0.deb
+      - name: FTP Deploy
+        uses: SamKirkland/FTP-Deploy-Action@4.3.0
+        with:
+          server: ${{ secrets.FTP_SERVER }}
+          username: ${{ secrets.FTP_USERNAME }}
+          password: ${{ secrets.FTP_PASSWORD }}
+          local-dir: ./
+          exclude: |
+            .git*
+            .github*
+            tests/*
+            box.json
+            commandbox-debian-6.2.0.deb
 
-  # reinit:
-  #   name: Reinitialize Application
-  #   runs-on: ubuntu-latest
-  #   needs: deploy  # Only run after successful deployment
+  reinit:
+    name: Reinitialize Application
+    runs-on: ubuntu-latest
+    needs: deploy  # Only run after successful deployment
 
-  #   steps:
-  #     - name: Send reinit request
-  #       run: |
-  #         echo "Reinitializing application..."
-  #         response=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.REINIT_URL }}")
+    steps:
+      - name: Send reinit request
+        run: |
+          echo "Reinitializing application..."
+          response=$(curl -s -o /dev/null -w "%{http_code}" "${{ vars.REINIT_URL }}")
           
-  #         if [ "$response" -eq 200 ]; then
-  #           echo "Application reinitialized successfully"
-  #         else
-  #           echo "::error::Failed to reinitialize application. HTTP Status: $response"
-  #           exit 1
-  #         fi
+          if [ "$response" -eq 200 ]; then
+            echo "Application reinitialized successfully"
+          else
+            echo "::error::Failed to reinitialize application. HTTP Status: $response"
+            exit 1
+          fi
