Updated code

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,19 +7,6 @@ on:
     branches: [main, staging]
 
 jobs:
-  acfcompile:
-    runs-on: ubuntu-latest
-    container:
-      image: adobecoldfusion/coldfusion2021:2021.0.13
-    env:
-      acceptEULA: YES
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
-
-      # Runs the cfcompile command inside the docker container
-      - name: Compile CFML
-        run: /opt/coldfusion/cfusion/bin/cfcompile.sh -cfruntimeuser root -webroot $GITHUB_WORKSPACE -dir $GITHUB_WORKSPACE
   cfcompile:
     runs-on: ubuntu-latest
     steps:
@@ -32,7 +19,7 @@ jobs:
   test:
     name: Run TestBox Tests
     runs-on: ubuntu-latest
-    needs: [cfcompile, acfcompile]  # Only run after successful compilation and code checking
+    needs: [cfcompile]  # Only run after successful compilation and code checking
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -42,18 +29,18 @@ jobs:
         env:
             TESTKEY: ${{ vars.TESTKEY }}
         with:
-          run: box start
-              box testbox run --directory=tests.specs > test-results.txt
-
-              failedCount=$(grep -oP '\[Failed:\s+\K\d+' test-results.txt)
-
-              if [ "$failedCount" -ne 0 ]; then
-                echo "::error::Some tests failed"
-                cat test-results.txt
-                exit 1
-              fi
-
-              echo "All tests passed successfully"
+          entrypoint: /opt/box/box
+          args: start
+              testbox run --directory=tests.specs > test-results.txt
+      - name: Check Test Results
+        run: |
+          failedCount=$(grep -oP '\[Failed:\s+\K\d+' test-results.txt)
+          if [ "$failedCount" -ne 0 ]; then
+            echo "::error::Some tests failed"
+            cat test-results.txt
+            exit 1
+          fi
+          echo "All tests passed successfully"
   # ftp_deploy:
   #   name: FTP Deploy
   #   runs-on: ubuntu-latest
