Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,16 +28,24 @@ jobs:
           box version
 
 
-      - name: Start Lucee Server and Run Tests
+      - name: Run TestBox Tests
         run: |
           box install
           box install testbox
           box server start port=8080 --background
-          sleep 10  # Wait for server to start
-          box testbox run runner='http://127.0.0.1:8080/tests/runner.cfm'
+          sleep 10
+          curl -s http://127.0.0.1:8080/tests/runner.cfm?testkey=1 > result.json
+          cat result.json
         env:
           CFENGINE: lucee
-
+      - name: Check Test Results
+        run: |
+          if grep -q '"status":"failed"' result.json; then
+            echo "❌ Tests failed"
+            exit 1
+          else
+            echo "✅ Tests passed"
+          fi
   # deploy:
   #   name: FTP Deploy
   #   runs-on: ubuntu-latest
